- pipeline:
    name: check
    manager: independent
    success-message: "Please confirm results. Contact info: networking.spp.integration@gmail.com . For more information, see https://wiki.openstack.org/wiki/ThirdPartySystems/Networking-spp_Integration_CI"
    failure-message: "Please confirm results. Contact info: networking.spp.integration@gmail.com . For more information, see https://wiki.openstack.org/wiki/ThirdPartySystems/Networking-spp_Integration_CI"
    trigger:
      gerrit:
        - event: patchset-created
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*test(( (?:bug|lp)[\s#:]*(\d+))|( no bug)|( m)|())\s*$
    success:
      gerrit:
        Verified: 1
    failure:
      gerrit:
        Verified: -1

- job:
    name: networking-spp-tempest-test
    parent: null
    run: playbooks/networking-spp-tempest/networking-spp-tempest.yaml
    nodeset:
      nodes:
        - name: controller1
          label: spp-install-ct
        - name: compute1
          label: spp-install-cp
        - name: compute2
          label: spp-install-cp
      groups:
        - name: controller
          nodes:
            - controller1
        - name: compute
          nodes:
            - compute1
            - compute2
    group-vars:
      controller:
        nodetype: "ctrl" 
      compute:
        nodetype: "compute" 
    voting: false

- project:
    name: networking-spp
    check:
      jobs:
        - networking-spp-tempest-test

- nodeset:
    name: nodeset-networking-spp
    nodes:
      - name: testvm
        label: spp-install-ct
    groups:
      - name: test
        nodes:
          - testvm
