- job:
    name: networking-spp-tempest-test
    parent: base

- project:
    networking-spp-integration-ci:
      jobs:
        - networking-spp-tempest-test
    templates:
      - openstack-python35-jobs
      - openstack-python36-jobs
